### ISSUE TITLE
User database is lost during upgrades

### ISSUE THREAD

**Issue by fraenki** [andeman/puppet-baculaweb#7] opened 2022-12-21 15:22 UTC
When upgrading Bacula-Web to a new version, the file containing the user database is lost:

```
bacula-web/application/assets/protected/application.db
```

Ideas:
* introduce a new parameter `$data_dir` which will hold these files
* add an `Exec` resource to migrate the "protected" folder to this new location
* add a symlink: `bacula-web/application/assets/protected` -> `$data_dir/protected`

@andeman, what do you think about this proposal?

Side note: future versions of Bacula-Web will _enforce_ user authentication, so now seems to be the right time to solve this issue.

**Comment by dfranco** [comment] 2022-12-25 11:15
Hi,

Let me introduce myself 

I'm maintainer of bacula-web project I'd like to give you more highlights and elaborate a bit more what"next release of bacula-web will enforce user authentication" means if you don't mind.

As of now, bacula-web only supports one kind of authentication by design, which is database user authentication (using a SQLite database).

What I initially planned for next major release was to enforce user authentication but I think I've changed a bit my mind about this specific topic.

For instance, some users uses LDAP through their web server configuration, some others uses basic authentication.

The main purpose of users database was not only to perform authentication, but also to store other users related settings (which will come in major versions).

So, does bacula-web will enforce user authentication, the answer is yes. But there will be "wrappers" for people using other authentication mechanisms.
I'll make sure the "transitions" will be as smooth as possible while upgrading to next major release.

Regarding this upgrade issue, I don't understand why upgrading drops the user db file, if I can help on that matter I'd be more than happy.

**Comment by fraenki** [comment] 2022-12-25 12:04
Hi @dfranco, thanks for the clarification.

> Regarding this upgrade issue, I don't understand why upgrading drops the user db file, if I can help on that matter I'd be more than happy.

The user database is lost due to the way this module handles upgrades. Basically this module installs every version in a _new_ directory and just maintains a symlink which points to the desired release. So you'll always get a "fresh" installation and the module needs to deal with persistent data, either by copying it to the new release or by using symlinks.

I don't think this is something that Bacula-Web should change, we just need to figure out the best way for this Puppet module to handle persistent data. Not a big deal, I guess. :)

**Comment by andreas-stuerz** [comment] 2023-01-20 23:24
fixed by https://github.com/andeman/puppet-baculaweb/pull/8

**Closed as completed by andreas-stuerz** 2023-01-20 23:24 UTC
